export const BMovies = [
    {
        id: "11",
        name: "Gadar",
        releaseYear: 2001,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/gadar--ek-prem-katha-et00002956-24-03-2017-19-52-43.jpg"
    },
    {
        id: "12",
        name: "Kabir Singh",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BNTVjMjExNWEtOWFiNS00ZTE2LWI0ODMtZTFlNDZiZWQ4MWVjXkEyXkFqcGdeQXVyNjcyNjMzMjQ@._V1_.jpg"
    },
    {
        id: "13",
        name: "Jung",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BMTI5MzgxOTYyNV5BMl5BanBnXkFtZTcwMjgxNDE0MQ@@._V1_.jpg"
    },
    {
        id: "14",
        name: "RRR",
        releaseYear: 2022,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BODUwNDNjYzctODUxNy00ZTA2LWIyYTEtMDc5Y2E5ZjBmNTMzXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
    },
    {
        id: "15",
        name: "Pushpa",
        releaseYear: 2000,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 9,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2021/12/allu-arjun-opens-up-about-his-plans-for-pushpa-2-001.jpg"
    },
    {
        id: "16",
        name: "Jannat",
        releaseYear: 2004,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 9,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://images-na.ssl-images-amazon.com/images/I/91iiaDveGFL._RI_.jpg"
    },
    {
        id: "17",
        name: "Rockstar",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@._V1_.jpg"
    },
    {
        id: "18",
        name: "War",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BNTlmNDMzOWQtYzg4Ny00OWQ0LWFhN2MtNmQ2MDczZGZhNTU5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
    },
    {
        id: "19",
        name: "MissionImpossible",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://m.media-amazon.com/images/M/MV5BOTFmNDA3ZjMtN2Y0MC00NDYyLWFlY2UtNTQ4OTQxMmY1NmVjXkEyXkFqcGdeQXVyNTg4NDQ4NDY@._V1_.jpg"
    },
    {
        id: "20",
        name: "Gabbar",
        releaseYear: 1999,
        certificate: "A",
        runtime: "139 min",
        genre: "Drama",
        imdbRating: 8.8,
        overview: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        metaScore: "66",
        director: "David Fincher",
        imgUrl: "https://jiocinemaweb.cdn.jio.com/jioimages.cdn.jio.com/content/entry/dynamiccontent/thumbs/1680/-/0/95/73/0_q7ct0csh_1531492829698_l_medium.jpg"
    },
]